### ISSUE TITLE
Imhotep front-end instances cannot connect to zookeeper

### ISSUE THREAD

**Issue by brownoxford** [indeedeng/imhotep-cloudformation#4]
I'm working with the cloudformation template and have found that the iql service is unavailable because the front-end instance is not able to contact zookeeper.

I was able to add security group rules manually, but it would be ideal if the cloudformation template took care of the necessary setup.

**Comment by youknowjack** [comment]
Thanks for the feedback. I've not encountered this out of the box, so it may be a untested combination of choices that triggers it, or possibly policy on your AWS account, or just a bug that has crept in due to changes in CloudFormation. I will look into it in the next week or two to see if I can reproduce the behavior.

**Comment by brownoxford** [comment]
I have a feeling that it's my particular setup that has not been part of testing - our default SG does not allow unlimited traffic inside of the VPC.
